" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" Affiche les numéros de lignes
set number

" Indentation toutes les 4 colonnes
set tabstop=4

" Indentation de 4 colonnes
set shiftwidth=4

" Indentation intelligent
set smartindent

" Conserve l'indentation courante sur les nouvelles lignes
set autoindent

" Retours arrières intelligents
set backspace=indent,eol,start 

" Indentation à la marque de Tab la plus proche
set shiftround

" Ctrl-S comme racourci de sauvegarde
inoremap <c-s> <c-o>:update<CR>
nnoremap <c-s> :update<CR>

"Ctrl-Z comme racourci pour precedent
inoremap <c-z> <c-o>:undo<CR>
nnoremap <c-z> :undo<CR>

" Ctrl-Y comme pour suivant
inoremap <c-y> <c-o>:redo<CR>
nnoremap <c-y> :redo<CR>

"Ctrl-c et Ctrl-p Copier/coller
vnoremap <c-c> y<Esc>i
inoremap <c-v> <c-o>P

" mode visual pour la selection
inoremap <s-left> <Esc>v

"sauver le fichier
inoremap <F12> <c-o>:saveas 

"QUitter l'application en mode insertion
inoremap <c-w> <Esc>:q<CR>

"autcompletion latex
autocmd Filetype tex source ~/.vim/auctex.vim

" Octave syntax
 augroup filetypedetect
   au! BufRead,BufNewFile *.m,*.oct set filetype=octave
 augroup END 

" set nowraping
set nowrap
set listchars=eol:¶,tab:→→,space:·
set listchars+=precedes:<,extends:>
set list

autocmd BufNewFile *.py 0read ~/.vim/python/skeleton

set textwidth=80
