---
# Install a developer environment
# ansible-playbook ansible/docker_ubuntu.yml -e ansible_python_interpreter=/usr/bin/python3 -K --become

- name: "Setup docker environment"
  hosts: docker-target
  become: true
  become_method: su

  tasks:
  - name: Update apt cache
    apt: update_cache=yes

  - name: Remove old versions
    apt: name={{ item }} state=absent
    with_items:
        - docker
        - docker-engine
        - docker.io

  - name: Install packages to allow apt to use a repository over HTTPS
    apt: name={{ item }} state=present
    with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

  - name: Add docker official GPG key
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
      state: present

  - name: Set docker stable repository
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
        state: present

  - name: Update apt cache
    apt: update_cache=yes

  - name: Install docker CE
    apt: name=docker-ce state=present

  - name: Check if docker is installed
    command: docker --version
    register: out
  - debug: var=out.stdout

  - name : Ensure group docker exists
    group:
      name: docker
      state: present

  - name: Enable docker on boot
    systemd:
        name: docker
        enabled: true
