---
# Install dokuwiki
- name: "Setup dokuwiki"
  hosts: mbwira

  become: true
  
  tasks:
  - name: "Update apt cache"
    apt: update_cache=yes

  - name: "Install lighttpd"
    apt: name=lighttpd state=present

  - name: "Install php7-cgi"
    apt: name=php7.0-cgi state=present

  - name: "Install php7.0-xml"
    apt: name=php7.0-xml state=present
  
  - name: "Install php7.0-gd"
    apt: name=php7.0-gd state=present
    notify:
      - Enable fastcgi
      - Enable fastcgi-php
      - Restart lighttpd

  - name: "Download and Extract dokuwiki"
    unarchive:
      src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
      dest: /var/www/html
      remote_src: yes
      list_files: yes
      owner: www-data
      group: www-data
    register: dokuwiki_folder

  - name: "Move dokuwiki.x.y.z to dokuwiki"
    command: mv /var/www/html/{{dokuwiki_folder.files[0]}} /var/www/html/dokuwiki

  handlers:
  - name: Enable fastcgi
    command: lighty-enable-mod fastcgi

  - name: Enable fastcgi-php
    command: lighty-enable-mod fastcgi-php
 
  - name: Restart lighttpd
    service: name=lighttpd state=restarted
